#!/usr/bin/env bash
set -euo pipefail

# Run one constant-command circle and record a bag usable for both tire/
# steering identification and residual-dynamics extraction.  The target
# kinematic radius is intentionally fixed here; direction and speed are the
# experiment variables supplied by the caller.

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RADIUS_M=2.5
MAX_SPEED_MPS=4.5
# At the configured maximum speed, v^2/R = 8.10 m/s^2.  Keep a small numeric
# allowance while still rejecting values inconsistent with this fixed profile.
MAX_LATERAL_ACCEL_MPS2=8.2
DEFAULT_DURATION_S=30
OUTPUT_DIR="$ROOT/lateral_identification/data/fixed_radius_r2p5"

usage() {
  cat <<'EOF'
Usage:
  ./scripts/record_circle_r2p5.sh [--plan] DIRECTION SPEED_MPS [DURATION_S] [RUN_ID]

Arguments:
  DIRECTION   left/l/ccw/左 or right/r/cw/右
  SPEED_MPS   speed command in [0.2, 4.5] m/s
  DURATION_S  active circle duration, at least 10 s (default: 30)
  RUN_ID      optional unique bag name (a timestamped name is generated by default)

Examples:
  ./scripts/record_circle_r2p5.sh --plan left 1.5
  ./scripts/record_circle_r2p5.sh left 1.5
  ./scripts/record_circle_r2p5.sh right 2.0 30

The script publishes real commands to /tianracer/ackermann_cmd. It refuses to
start while MPCC or any other command publisher owns that topic. Press Ctrl-C
once to send zero speed and finalize the bag.
EOF
}

plan_only=false
if [[ "${1:-}" == "--plan" ]]; then
  plan_only=true
  shift
fi
if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi
if (( $# < 2 || $# > 4 )); then
  usage >&2
  exit 2
fi

case "${1,,}" in
  left|l|ccw|左|左转) direction=left ;;
  right|r|cw|右|右转) direction=right ;;
  *)
    echo "[FAIL] DIRECTION must be left/right (also accepts l/r, ccw/cw, 左/右)." >&2
    exit 2
    ;;
esac
speed="$2"
duration="${3:-$DEFAULT_DURATION_S}"

# Keep generated names shell- and rosbag-friendly without changing the value
# passed to the numeric validator in run_circle_prbs.py.
speed_tag="${speed//./p}"
speed_tag="${speed_tag//+/_}"
speed_tag="${speed_tag//-/_}"
stamp="$(date +%Y%m%d_%H%M%S)"
run_id="${4:-circle_r2p5_${direction}_v${speed_tag}_${stamp}}"
if [[ ! "$run_id" =~ ^[A-Za-z0-9_-]+$ ]]; then
  echo "[FAIL] RUN_ID may contain only letters, numbers, underscore, and dash." >&2
  exit 2
fi

source "$ROOT/scripts/ros_env.sh"

args=(
  "$run_id"
  --radius "$RADIUS_M"
  --speed "$speed"
  --max-speed "$MAX_SPEED_MPS"
  --direction "$direction"
  --excitation-deg 0
  --duration "$duration"
  --pre-zero 2
  --post-zero 3
  --max-lateral-accel "$MAX_LATERAL_ACCEL_MPS2"
  --output-dir "$OUTPUT_DIR"
)
if [[ "$plan_only" == true ]]; then
  args+=(--plan)
else
  echo "[REAL VEHICLE] target radius=${RADIUS_M} m, direction=$direction, speed=$speed m/s"
  echo "[RECORD] one bag for constant-circle identification + residual dynamics"
  echo "[HIGH RISK] At 4.5 m/s this profile requests about 8.1 m/s^2 lateral acceleration."
  echo "[SAFETY] Stop MPCC first, clear a circle of at least 3.5 m radius, and keep emergency stop ready."
fi

exec python3 "$ROOT/lateral_identification/run_circle_prbs.py" "${args[@]}"
