#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CANDIDATE="stable_v5"
TRACK="racelinev3_stable_v5_fast5_std32"
CONTROLLER_CONFIG="candidates/$CANDIDATE/controller.yaml"
VEHICLE_CONFIG="candidates/$CANDIDATE/vehicle.yaml"
CONTROLLER="$ROOT/src/f1tenth_dynamic_mpcc/config/$CONTROLLER_CONFIG"
VEHICLE="$ROOT/src/f1tenth_dynamic_mpcc/config/$VEHICLE_CONFIG"
LAUNCH="$ROOT/src/f1tenth_dynamic_mpcc/launch/hardware_mpcc_stable_v5.launch"
TRACK_CSV="$ROOT/src/f1tenth_dynamic_mpcc/data/tracks/$TRACK/raceline.csv"
SPEED_ZONES="$ROOT/src/f1tenth_dynamic_mpcc/data/tracks/$TRACK/speed_zones.csv"
MPCC_NODE="$ROOT/src/f1tenth_dynamic_mpcc/src/mpcc_node_stable_v5.cpp"
CORE_HEADER="$ROOT/src/f1tenth_dynamic_mpcc/include/f1tenth_dynamic_mpcc/core.hpp"
CORE_SOURCE="$ROOT/src/f1tenth_dynamic_mpcc/src/core.cpp"
TRACKING_GATE_HEADER="$ROOT/src/f1tenth_dynamic_mpcc/include/f1tenth_dynamic_mpcc/stable_v5_tracking_gate.hpp"
TELEMETRY_LOGGER="$ROOT/src/f1tenth_dynamic_mpcc/scripts/telemetry_logger.py"
SUPERVISOR="$ROOT/src/f1tenth_dynamic_mpcc/scripts/automatic_relaunch_supervisor.py"
MOTION_LOGIC="$ROOT/src/f1tenth_dynamic_mpcc/python/f1tenth_dynamic_mpcc/automatic_relaunch.py"
PLACEMENT_LOGIC="$ROOT/src/f1tenth_dynamic_mpcc/python/f1tenth_dynamic_mpcc/quick_relaunch.py"
RECORDER="$ROOT/scripts/record_stable_v5_bag.sh"
RESIDUAL="$ROOT/src/f1tenth_dynamic_mpcc/config/residual/residual_stable_v3_racelinev3_h3_scale030.yaml"

check_hash() {
  local expected="$1"
  local path="$2"
  local actual
  actual="$(sha256sum "$path" | awk '{print $1}')"
  if [[ "$actual" != "$expected" ]]; then
    echo "[FAIL] Stable V5 frozen file changed: $path" >&2
    echo "       expected=$expected" >&2
    echo "       actual=$actual" >&2
    exit 1
  fi
}

# Stable V5 is immutable: validate every behavior-defining release file.
check_hash "40b89b20179510642a3c1f7c649deb92d8ae487e6d3f3241a0f158466611da41" "$CONTROLLER"
check_hash "fd5f9d91bc1fe967d7429cb12f42d982e8527d0d8e559f41dbefd8f2cf24366d" "$VEHICLE"
check_hash "88ca2acf725207a68d0ea20aa9e26d8af93dcff027afd235b9ce2045f866b82a" "$TRACK_CSV"
check_hash "3ace10062380356525c99d02e07d61f125c971b476594bdd4c26c2da6f250132" "$SPEED_ZONES"
check_hash "a258e650d0a66192a0eae5256267159f1786e14bffe55cd745098e88bbaa68ca" "$LAUNCH"
check_hash "95a13797eb762132c47928dde83aa454b62d9a344154ddbae4b90b8b612a2d44" "$RESIDUAL"
check_hash "c97c5b7f745f5fd9fba2dede51898b63974209ccaf0ea0496adcb2becb5118f4" "$MPCC_NODE"
check_hash "ca9d46a11a4fe40917162ed4235204209d71d88b50028f81d65b771f36e141aa" "$CORE_HEADER"
check_hash "28e3c2535c1e0fcd1eeb121ef110be2132e6afb816e9391c289f980ab6badc17" "$CORE_SOURCE"
check_hash "32540f20176a6761ee015429c05544cc137d4334f0a951b91bd9f3446a79c2ae" "$TRACKING_GATE_HEADER"
check_hash "2de61dbdb3c27b56bf2800c14c739b140dbcc4e0ea49532158c56838485f3a17" "$TELEMETRY_LOGGER"
check_hash "f9996adfb6c59f66a2ccaf7522f40825e2c74a9e3370c7f8ffc5e4fa1a22545a" "$SUPERVISOR"
check_hash "43760fcbb6a965da5c7d8e68b7683a2a520d2129da30dcc8d4eff8db2521a8d6" "$MOTION_LOGIC"
check_hash "21217b67871accf841c1bef76f9e6c7f874526cfd1bd99c497706b989cb7b178" "$PLACEMENT_LOGIC"
check_hash "1ebd7a7a5b4b5531058206b3a64377b5bb17ff03643d97bbb5dc294d695302ec" "$RECORDER"

ACTION="${1:-mpcc}"
if [[ "$ACTION" == "--check-only" ]]; then
  echo "[OK] Stable V5 frozen hashes match"
  echo "[OK] carry recovery, quick launch, dual-grid race start and gradual high-speed gate are enabled"
  exit 0
fi

PREPARE_ONLY=false
if [[ "$ACTION" == "--prepare-only" ]]; then
  PREPARE_ONLY=true
elif [[ "$ACTION" != "mpcc" ]]; then
  echo "usage: $0 [mpcc|--check-only|--prepare-only]" >&2
  exit 2
fi

GENERATED_DIR="${MPCC_GENERATED_DIR:-$HOME/.cache/f1tenth_residual_mpcc/acados_stable_v5}"
if [[ -z "${RESIDUAL_DYNAMICS_WS:-}" ]] \
   && [[ ! -f "$(dirname "$ROOT")/f1tenth_residual_ws/devel/setup.bash" ]]; then
  export RESIDUAL_DYNAMICS_WS="$ROOT"
fi
source "$ROOT/scripts/ros_env.sh"
# LocalizationStatus is generated by the localization workspace, which is not
# an underlay of the residual/controller workspaces on the car. Extend after
# ros_env.sh so the latter cannot reset the message's ROS/Python paths.
LOCALIZATION_WS="${AUTO_RELAUNCH_LOCALIZATION_WS:-/home/tianbot/localization_main}"
if [[ ! -f "$LOCALIZATION_WS/devel/setup.bash" ]]; then
  echo "[FAIL] localization workspace setup is missing: $LOCALIZATION_WS/devel/setup.bash" >&2
  exit 1
fi
MPCC_RESTORE_NOUNSET=false
case "$-" in
  *u*) MPCC_RESTORE_NOUNSET=true ;;
esac
set +u
source "$LOCALIZATION_WS/devel/setup.bash" --extend
if [[ "$MPCC_RESTORE_NOUNSET" == true ]]; then
  set -u
fi
unset MPCC_RESTORE_NOUNSET
export PYTHONPATH="$ROOT/src/f1tenth_dynamic_mpcc/python${PYTHONPATH:+:$PYTHONPATH}"
python3 -c 'from point_lio_sam_lighterbev.msg import LocalizationStatus' || {
  echo "[FAIL] point_lio_sam_lighterbev/LocalizationStatus is not importable" >&2
  exit 1
}
export MPCC_GENERATED_DIR="$GENERATED_DIR"
export MPCC_TRACK="$TRACK"
export MPCC_CONTROLLER_CONFIG="$CONTROLLER_CONFIG"
export MPCC_VEHICLE_CONFIG="$VEHICLE_CONFIG"
export MPCC_RESIDUAL_MODEL_PATH="$RESIDUAL"
export MPCC_RESIDUAL_FEATURE_SET="markov_v1"
export MPCC_COST_CONTOUR_OVERRIDE="45.0"
export MPCC_COST_HEADING_RACE_OVERRIDE="1.0"
export MPCC_COST_STEERING_COMMAND_RATE_OVERRIDE="0.60"
"$ROOT/scripts/ensure_acados_solvers.sh"

if [[ "$PREPARE_ONLY" == "true" ]]; then
  echo "[OK] Stable V5 solvers are ready; hardware was not started"
  exit 0
fi

"$ROOT/scripts/check_mpcc_topics.sh"

require_localization_rate_param() {
  local name="$1"
  local expected="$2"
  local value
  value="$(rosparam get "$name" 2>/dev/null || true)"
  if ! awk -v value="$value" -v expected="$expected" \
    'BEGIN { exit !(value != "" && (value-expected < 1e-6) && (expected-value < 1e-6)) }'; then
    echo "[FAIL] localization frequency profile mismatch: $name=$value expected=$expected" >&2
    exit 1
  fi
}

# PointLIO supplies unique 60 Hz sensor-time states. The robust localizer keeps
# queue_size=1 and an unlimited latest-sample output cap (0.0), while the
# expensive global map->odom correction remains the accepted 5 Hz backend.
require_localization_rate_param "/laserMapping/odometry/max_publish_hz" "60.0"
require_localization_rate_param "/pointlio_robust_localizer/control_output_hz" "0.0"
require_localization_rate_param "/pointlio_robust_localizer/backend_hz" "5.0"

RESIDUAL_MPCC_SPEED_CAP="${RESIDUAL_MPCC_SPEED_CAP:-5.0}"
if ! awk -v value="$RESIDUAL_MPCC_SPEED_CAP" \
  'BEGIN { exit !(value > 0.0 && value <= 5.0) }'; then
  echo "[FAIL] RESIDUAL_MPCC_SPEED_CAP must be in (0, 5.0]" >&2
  exit 2
fi

mkdir -p "$ROOT/log"
STAMP="$(date +%Y%m%d_%H%M%S)"
RECORD_PID=""
if [[ "${MPCC_RECORD_BAG:-false}" == "true" ]]; then
  mkdir -p "$ROOT/bags"
  BAG_PATH="${MPCC_RECORD_BAG_PATH:-$ROOT/bags/stable_v5_${STAMP}.bag}"
  "$RECORDER" "$BAG_PATH" &
  RECORD_PID=$!
  echo "[RECORD] automatic-relaunch analysis bag -> $BAG_PATH"
  trap 'kill -INT "$RECORD_PID" 2>/dev/null || true' EXIT
fi

echo "[STABLE_V5] frozen Stable V3 residual MPCC race release"
echo "[BRAKE4_ASYM_60HZ] MPCC solve=60 Hz; command publisher=60 Hz; supervisor/hardware mux=60 Hz"
echo "[STABLE_V5] validated 60 Hz solve/publisher/supervisor pipeline; overlap guard remains active"
echo "[BRAKE4_ASYM] normal publisher decel=4.0 m/s^2; fallback remains 4.0 m/s^2"
echo "[BRAKE4_ASYM] raceline profile decel=4.0 m/s^2"
echo "[BRAKE4_ASYM] acceleration delay/tau=0.13/0.20 s; braking delay/tau=0.06/0.166 s"
echo "[AUTO_RELAUNCH] StableV3 residual + frozen 5.0/3.2 m/s raceline profile"
echo "[AUTO_RELAUNCH] operator workflow: hold E-stop -> carry/place -> release E-stop"
echo "[AUTO_RELAUNCH] carry: wheel<=0.10 + z/xy/yaw/tilt evidence; ground window=0.30 s"
echo "[AUTO_RELAUNCH] guarded release launch=2.0 m/s; checkpoint PP target=2.0 m/s; accel=2.4 m/s^2"
echo "[AUTO_RELAUNCH] global S + safe forward PP target; recovery angle<=60 deg"
echo "[AUTO_RELAUNCH] alternating grid radius=2.0 m: launch=4.0 m/s; 2.5 m merge; handoff>=3.0 m/s"
echo "[AUTO_RELAUNCH] recovery PP: 2.0 m/s base, curvature/error adaptive >=1.2 m/s"
echo "[AUTO_RELAUNCH] recovery PP->MPCC: dynamic threshold=max(1.0,min(1.8,PP-0.2)) m/s"
echo "[AUTO_RELAUNCH] handoff steering diff<=0.08 rad for 3 samples + 0.20 s blend"
echo "[AUTO_RELAUNCH] runtime cap=${RESIDUAL_MPCC_SPEED_CAP} m/s; fast zones=5.0, ordinary=3.2"
echo "[TRACK_GATE] speed above 3.2 m/s is released continuously by lateral/heading/margin quality"
echo "[TRACK_GATE] full speed: |ey|<=0.10 m, |epsi|<=0.04 rad, buffered margin>=0.30 m"
echo "[TRACK_GATE] base speed: |ey|>=0.30 m, |epsi|>=0.12 rad, or buffered margin<=0.12 m"
echo "[TRACK_GATE] predicted soft margin=0.15 m; PP current-margin trigger=0.10 m"
echo "[AUTO_RELAUNCH] hardware output=${AUTO_RELAUNCH_HARDWARE_COMMAND_TOPIC:-/tianracer/ackermann_cmd}"
echo "[STABLE_V5] StableV3, StableV4 and all prior candidates remain unchanged"
echo "[WARNING] Hold the physical E-stop before launch. A valid ground placement arms the 2.0 m/s PP launch command."

LAUNCH_ARGS=(
  track:="$TRACK"
  controller_config:="$CONTROLLER_CONFIG"
  vehicle_config:="$VEHICLE_CONFIG"
  formulation:=mpcc
  allow_real_hardware:=true
  rviz:="${MPCC_REMOTE_RVIZ:-false}"
  runtime_speed_cap_mps:="$RESIDUAL_MPCC_SPEED_CAP"
  generated_dir:="$GENERATED_DIR"
  residual_model_path:="$RESIDUAL"
  residual_feature_set:=markov_v1
  hardware_command_topic:="${AUTO_RELAUNCH_HARDWARE_COMMAND_TOPIC:-/tianracer/ackermann_cmd}"
  telemetry_path:="$ROOT/log/hardware_stable_v5_${STAMP}.jsonl"
  lap_timer:="${AUTO_RELAUNCH_LAP_TIMER:-true}"
  lap_log_path:="$ROOT/log/laps_stable_v5_${STAMP}.csv"
)

if [[ -n "$RECORD_PID" ]]; then
  roslaunch f1tenth_dynamic_mpcc \
    hardware_mpcc_stable_v5.launch \
    "${LAUNCH_ARGS[@]}"
else
  exec roslaunch f1tenth_dynamic_mpcc \
    hardware_mpcc_stable_v5.launch \
    "${LAUNCH_ARGS[@]}"
fi
