#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Keep the canonical V1 model and original controller configuration intact.
# This profile adds damped raceline tracking and tiered safety arbitration.
export MPCC_COST_CONTOUR_OVERRIDE="${MPCC_COST_CONTOUR_OVERRIDE:-45.0}"
export MPCC_COST_HEADING_RACE_OVERRIDE="${MPCC_COST_HEADING_RACE_OVERRIDE:-1.0}"
export MPCC_COST_STEERING_COMMAND_RATE_OVERRIDE="${MPCC_COST_STEERING_COMMAND_RATE_OVERRIDE:-0.90}"
export MPCC_RISK_TIERING_ENABLED="${MPCC_RISK_TIERING_ENABLED:-true}"
export MPCC_NEAR_TRACK_HORIZON_OVERRIDE="${MPCC_NEAR_TRACK_HORIZON_OVERRIDE:-0.40}"
export MPCC_PREDICTIVE_SPEED_HOLD_OVERRIDE="${MPCC_PREDICTIVE_SPEED_HOLD_OVERRIDE:-0.50}"
export MPCC_PREDICTIVE_SPEED_RECOVERY_OVERRIDE="${MPCC_PREDICTIVE_SPEED_RECOVERY_OVERRIDE:-1.0}"
export MPCC_PP_CURRENT_MARGIN_OVERRIDE="${MPCC_PP_CURRENT_MARGIN_OVERRIDE:-0.02}"
export MPCC_PP_CONFIRMATION_CYCLES_OVERRIDE="${MPCC_PP_CONFIRMATION_CYCLES_OVERRIDE:-2}"
export MPCC_V1_GENERATED_DIR="${MPCC_V1_TRACKING_GENERATED_DIR:-$HOME/.cache/f1tenth_residual_mpcc/v1_tracking_qc45_qh1p0_qdu0p9}"

echo "[PROFILE] V1 tracking: contour=$MPCC_COST_CONTOUR_OVERRIDE heading_race=$MPCC_COST_HEADING_RACE_OVERRIDE steering_rate_cost=$MPCC_COST_STEERING_COMMAND_RATE_OVERRIDE"
echo "[PROFILE] tiered risk: near=${MPCC_NEAR_TRACK_HORIZON_OVERRIDE}s confirm=${MPCC_PP_CONFIRMATION_CYCLES_OVERRIDE} cycles hold=${MPCC_PREDICTIVE_SPEED_HOLD_OVERRIDE}s recovery=${MPCC_PREDICTIVE_SPEED_RECOVERY_OVERRIDE}m/s^2"
exec "$ROOT/scripts/start_mpcc_hardware_v1.sh" "${1:-mpcc}"
