#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BASE_LAUNCHER="$ROOT/scripts/start_mpcc_hardware_stable_v3_5mps_auto_relaunch_candidate.sh"
CANDIDATE="stable_v3_5mps_auto_relaunch_brake4_asym_candidate"
TRACK="racelinev3_5mps_arc_straight_std3_candidate"
CONTROLLER_CONFIG="candidates/$CANDIDATE/controller.yaml"
VEHICLE_CONFIG="candidates/stable_v3_5mps_arc_straight_std3_candidate/vehicle.yaml"
CONTROLLER="$ROOT/src/f1tenth_dynamic_mpcc/config/$CONTROLLER_CONFIG"
VEHICLE="$ROOT/src/f1tenth_dynamic_mpcc/config/$VEHICLE_CONFIG"
LAUNCH="$ROOT/src/f1tenth_dynamic_mpcc/launch/hardware_mpcc_stable_v3_5mps_auto_relaunch_brake4_asym_candidate.launch"
MPCC_NODE="$ROOT/src/f1tenth_dynamic_mpcc/src/mpcc_node_auto_relaunch.cpp"
SUPERVISOR="$ROOT/src/f1tenth_dynamic_mpcc/scripts/automatic_relaunch_supervisor.py"
MOTION_LOGIC="$ROOT/src/f1tenth_dynamic_mpcc/python/f1tenth_dynamic_mpcc/automatic_relaunch.py"
PLACEMENT_LOGIC="$ROOT/src/f1tenth_dynamic_mpcc/python/f1tenth_dynamic_mpcc/quick_relaunch.py"
RECORDER="$ROOT/scripts/record_auto_relaunch_bag.sh"
RESIDUAL="$ROOT/src/f1tenth_dynamic_mpcc/config/residual/residual_stable_v3_racelinev3_h3_scale030.yaml"

check_hash() {
  local expected="$1"
  local path="$2"
  local actual
  actual="$(sha256sum "$path" | awk '{print $1}')"
  if [[ "$actual" != "$expected" ]]; then
    echo "[FAIL] automatic-relaunch candidate file changed: $path" >&2
    echo "       expected=$expected" >&2
    echo "       actual=$actual" >&2
    exit 1
  fi
}

# First prove that the exact automatic-relaunch baseline remains unchanged.
"$BASE_LAUNCHER" --check-only
check_hash "962ac26cb6724912e54b90ad3ea4a917c6da72c6c51e001f99fcf6371eb11c08" "$CONTROLLER"
check_hash "0a56d4a377338a964d5212d2b2e44e7abe5c47c0e9eb34a9ca38580ac8ef2757" "$LAUNCH"
check_hash "344bc7003ff491ff082351a2fb6979a608b9ead2df0238a0cee6c0d1b911bde0" "$MPCC_NODE"
check_hash "f9996adfb6c59f66a2ccaf7522f40825e2c74a9e3370c7f8ffc5e4fa1a22545a" "$SUPERVISOR"
check_hash "43760fcbb6a965da5c7d8e68b7683a2a520d2129da30dcc8d4eff8db2521a8d6" "$MOTION_LOGIC"
check_hash "21217b67871accf841c1bef76f9e6c7f874526cfd1bd99c497706b989cb7b178" "$PLACEMENT_LOGIC"
check_hash "195980306405286e88f26af75c3aec1912aad12a1bac389202f299b67972e283" "$RECORDER"

ACTION="${1:-mpcc}"
if [[ "$ACTION" == "--check-only" ]]; then
  echo "[OK] automatic-relaunch baseline is unchanged"
  echo "[OK] isolated brake4/asymmetric-longitudinal candidate hashes match"
  exit 0
fi

PREPARE_ONLY=false
if [[ "$ACTION" == "--prepare-only" ]]; then
  PREPARE_ONLY=true
elif [[ "$ACTION" != "mpcc" ]]; then
  echo "usage: $0 [mpcc|--check-only|--prepare-only]" >&2
  exit 2
fi

GENERATED_DIR="${MPCC_GENERATED_DIR:-$HOME/.cache/f1tenth_residual_mpcc/acados_stable_v3_5mps_auto_relaunch_brake4_asym}"
if [[ -z "${RESIDUAL_DYNAMICS_WS:-}" ]] \
   && [[ ! -f "$(dirname "$ROOT")/f1tenth_residual_ws/devel/setup.bash" ]]; then
  export RESIDUAL_DYNAMICS_WS="$ROOT"
fi
source "$ROOT/scripts/ros_env.sh"
# LocalizationStatus is generated by the localization workspace, which is not
# an underlay of the residual/controller workspaces on the car. Extend after
# ros_env.sh so the latter cannot reset the message's ROS/Python paths.
LOCALIZATION_WS="${AUTO_RELAUNCH_LOCALIZATION_WS:-/home/tianbot/localization_main}"
if [[ ! -f "$LOCALIZATION_WS/devel/setup.bash" ]]; then
  echo "[FAIL] localization workspace setup is missing: $LOCALIZATION_WS/devel/setup.bash" >&2
  exit 1
fi
MPCC_RESTORE_NOUNSET=false
case "$-" in
  *u*) MPCC_RESTORE_NOUNSET=true ;;
esac
set +u
source "$LOCALIZATION_WS/devel/setup.bash" --extend
if [[ "$MPCC_RESTORE_NOUNSET" == true ]]; then
  set -u
fi
unset MPCC_RESTORE_NOUNSET
export PYTHONPATH="$ROOT/src/f1tenth_dynamic_mpcc/python${PYTHONPATH:+:$PYTHONPATH}"
python3 -c 'from point_lio_sam_lighterbev.msg import LocalizationStatus' || {
  echo "[FAIL] point_lio_sam_lighterbev/LocalizationStatus is not importable" >&2
  exit 1
}
export MPCC_GENERATED_DIR="$GENERATED_DIR"
export MPCC_TRACK="$TRACK"
export MPCC_CONTROLLER_CONFIG="$CONTROLLER_CONFIG"
export MPCC_VEHICLE_CONFIG="$VEHICLE_CONFIG"
export MPCC_RESIDUAL_MODEL_PATH="$RESIDUAL"
export MPCC_RESIDUAL_FEATURE_SET="markov_v1"
export MPCC_COST_CONTOUR_OVERRIDE="45.0"
export MPCC_COST_HEADING_RACE_OVERRIDE="1.0"
export MPCC_COST_STEERING_COMMAND_RATE_OVERRIDE="0.60"
"$ROOT/scripts/ensure_acados_solvers.sh"

if [[ "$PREPARE_ONLY" == "true" ]]; then
  echo "[OK] automatic-relaunch candidate solvers are ready; hardware was not started"
  exit 0
fi

"$ROOT/scripts/check_mpcc_topics.sh"

RESIDUAL_MPCC_SPEED_CAP="${RESIDUAL_MPCC_SPEED_CAP:-5.0}"
if ! awk -v value="$RESIDUAL_MPCC_SPEED_CAP" \
  'BEGIN { exit !(value > 0.0 && value <= 5.0) }'; then
  echo "[FAIL] RESIDUAL_MPCC_SPEED_CAP must be in (0, 5.0]" >&2
  exit 2
fi

mkdir -p "$ROOT/log"
STAMP="$(date +%Y%m%d_%H%M%S)"
RECORD_PID=""
if [[ "${MPCC_RECORD_BAG:-false}" == "true" ]]; then
  mkdir -p "$ROOT/bags"
  BAG_PATH="${MPCC_RECORD_BAG_PATH:-$ROOT/bags/stable_v3_5mps_auto_relaunch_brake4_asym_${STAMP}.bag}"
  "$RECORDER" "$BAG_PATH" &
  RECORD_PID=$!
  echo "[RECORD] automatic-relaunch analysis bag -> $BAG_PATH"
  trap 'kill -INT "$RECORD_PID" 2>/dev/null || true' EXIT
fi

echo "[BRAKE4_ASYM] based on stable_v3_5mps_auto_relaunch_candidate"
echo "[BRAKE4_ASYM] normal publisher decel=4.0 m/s^2; fallback remains 4.0 m/s^2"
echo "[BRAKE4_ASYM] raceline profile decel=4.0 m/s^2"
echo "[BRAKE4_ASYM] acceleration delay/tau=0.13/0.20 s; braking delay/tau=0.06/0.166 s"
echo "[AUTO_RELAUNCH] stableV3 residual + accepted 5/3 m/s raceline profile"
echo "[AUTO_RELAUNCH] operator workflow: hold E-stop -> carry/place -> release E-stop"
echo "[AUTO_RELAUNCH] carry: wheel<=0.10 + z/xy/yaw/tilt evidence; ground window=0.30 s"
echo "[AUTO_RELAUNCH] guarded release launch=2.0 m/s; checkpoint PP target=2.0 m/s; accel=2.4 m/s^2"
echo "[AUTO_RELAUNCH] global S + safe forward PP target; recovery angle<=60 deg"
echo "[AUTO_RELAUNCH] map-origin race grid: aligned launch=3.0 m/s; handoff=2.7 m/s"
echo "[AUTO_RELAUNCH] recovery PP: 2.0 m/s base, curvature/error adaptive >=1.2 m/s"
echo "[AUTO_RELAUNCH] PP->MPCC: adaptive speed + steering diff<=0.08 rad for 3 samples + 0.20 s blend"
echo "[AUTO_RELAUNCH] runtime cap=${RESIDUAL_MPCC_SPEED_CAP} m/s; fast zones=5.0, standard=3.0"
echo "[AUTO_RELAUNCH] hardware output=${AUTO_RELAUNCH_HARDWARE_COMMAND_TOPIC:-/tianracer/ackermann_cmd}"
echo "[AUTO_RELAUNCH] baseline auto-relaunch, original 5 m/s launcher and stableV3 remain unchanged"
echo "[WARNING] Hold the physical E-stop before launch. A valid ground placement arms the 2.0 m/s PP launch command."

LAUNCH_ARGS=(
  track:="$TRACK"
  controller_config:="$CONTROLLER_CONFIG"
  vehicle_config:="$VEHICLE_CONFIG"
  formulation:=mpcc
  allow_real_hardware:=true
  rviz:="${MPCC_REMOTE_RVIZ:-false}"
  runtime_speed_cap_mps:="$RESIDUAL_MPCC_SPEED_CAP"
  generated_dir:="$GENERATED_DIR"
  residual_model_path:="$RESIDUAL"
  residual_feature_set:=markov_v1
  hardware_command_topic:="${AUTO_RELAUNCH_HARDWARE_COMMAND_TOPIC:-/tianracer/ackermann_cmd}"
  telemetry_path:="$ROOT/log/hardware_stable_v3_5mps_auto_relaunch_brake4_asym_${STAMP}.jsonl"
  lap_timer:="${AUTO_RELAUNCH_LAP_TIMER:-true}"
  lap_log_path:="$ROOT/log/laps_stable_v3_5mps_auto_relaunch_brake4_asym_${STAMP}.csv"
)

if [[ -n "$RECORD_PID" ]]; then
  roslaunch f1tenth_dynamic_mpcc \
    hardware_mpcc_stable_v3_5mps_auto_relaunch_brake4_asym_candidate.launch \
    "${LAUNCH_ARGS[@]}"
else
  exec roslaunch f1tenth_dynamic_mpcc \
    hardware_mpcc_stable_v3_5mps_auto_relaunch_brake4_asym_candidate.launch \
    "${LAUNCH_ARGS[@]}"
fi
