#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CANDIDATE="stable_v4_u_complex_std35_candidate"
TRACK="racelinev6_u_complex_std35_candidate"
CONTROLLER_CONFIG="candidates/$CANDIDATE/controller.yaml"
VEHICLE_CONFIG="candidates/stable_v4/vehicle.yaml"
CONTROLLER="$ROOT/src/f1tenth_dynamic_mpcc/config/$CONTROLLER_CONFIG"
VEHICLE="$ROOT/src/f1tenth_dynamic_mpcc/config/$VEHICLE_CONFIG"
LAUNCH="$ROOT/src/f1tenth_dynamic_mpcc/launch/hardware_mpcc_stable_v4_u_complex_std35_candidate.launch"
TRACK_CSV="$ROOT/src/f1tenth_dynamic_mpcc/data/tracks/$TRACK/raceline.csv"
MPCC_NODE="$ROOT/src/f1tenth_dynamic_mpcc/src/mpcc_node_auto_relaunch.cpp"
SUPERVISOR="$ROOT/src/f1tenth_dynamic_mpcc/scripts/automatic_relaunch_supervisor.py"
MOTION_LOGIC="$ROOT/src/f1tenth_dynamic_mpcc/python/f1tenth_dynamic_mpcc/automatic_relaunch.py"
PLACEMENT_LOGIC="$ROOT/src/f1tenth_dynamic_mpcc/python/f1tenth_dynamic_mpcc/quick_relaunch.py"
RECORDER="$ROOT/scripts/record_auto_relaunch_shadow_bag_candidate.sh"
SHADOW_TOPIC_LIST="$ROOT/scripts/record_lightweight_overtake_topics.sh"
AVOIDANCE="$ROOT/avoidance/scripts/start_avoidance.sh"
RESIDUAL="$ROOT/src/f1tenth_dynamic_mpcc/config/residual/residual_stable_v3_racelinev3_h3_scale030.yaml"

check_hash() {
  local expected="$1"
  local path="$2"
  local actual
  actual="$(sha256sum "$path" | awk '{print $1}')"
  if [[ "$actual" != "$expected" ]]; then
    echo "[FAIL] U-complex candidate file changed: $path" >&2
    echo "       expected=$expected" >&2
    echo "       actual=$actual" >&2
    exit 1
  fi
}

# Validate the Stable V4 core plus isolated candidate files. The candidate
# recorder is shadow-aware and does not replace the global recorder.
check_hash "576656925e91152ee720d4d50fd7d93890fbf2b629eb0fa650eb820c675b411e" "$CONTROLLER"
check_hash "fbe6f459a81deb2814c77c4d9b5b6b50769e36e3fda42e7ede865eb92460a778" "$VEHICLE"
check_hash "d6c84d646524af42cea43e744d439ada4e19e21e756f20a0c26e17ed45b15108" "$TRACK_CSV"
check_hash "95a13797eb762132c47928dde83aa454b62d9a344154ddbae4b90b8b612a2d44" "$RESIDUAL"
check_hash "f5500df9c17e816f8e431534c7e2f0fac3ad050ef20dab40d2f3ea88a0597ecc" "$LAUNCH"
check_hash "344bc7003ff491ff082351a2fb6979a608b9ead2df0238a0cee6c0d1b911bde0" "$MPCC_NODE"
check_hash "f9996adfb6c59f66a2ccaf7522f40825e2c74a9e3370c7f8ffc5e4fa1a22545a" "$SUPERVISOR"
check_hash "43760fcbb6a965da5c7d8e68b7683a2a520d2129da30dcc8d4eff8db2521a8d6" "$MOTION_LOGIC"
check_hash "21217b67871accf841c1bef76f9e6c7f874526cfd1bd99c497706b989cb7b178" "$PLACEMENT_LOGIC"
check_hash "69bdf0135ea19ca3f696838b683c329e18b6aa2ad79351412caec628259c173d" "$RECORDER"
check_hash "03f657b0f72f2c5081c85aa6abedd1d2f35843ac4d358cb65bb9de3a2536365b" "$SHADOW_TOPIC_LIST"

MPCC_ENABLE_SHADOW="${MPCC_ENABLE_SHADOW:-false}"
if [[ "$MPCC_ENABLE_SHADOW" != "true" && "$MPCC_ENABLE_SHADOW" != "false" ]]; then
  echo "[FAIL] MPCC_ENABLE_SHADOW must be true or false" >&2
  exit 2
fi
if [[ "$MPCC_ENABLE_SHADOW" == "true" ]]; then
  if [[ ! -x "$AVOIDANCE" ]]; then
    echo "[FAIL] shadow launcher is missing or not executable: $AVOIDANCE" >&2
    exit 1
  fi
  "$AVOIDANCE" --check-only
fi

ACTION="${1:-mpcc}"
if [[ "$ACTION" == "--check-only" ]]; then
  echo "[OK] Stable V4 base and isolated U-complex candidate hashes match"
  echo "[OK] U-complex raceline: standard=3.5, fast=5.0, profile decel=3.2"
  echo "[OK] optional shadow mode: $MPCC_ENABLE_SHADOW"
  exit 0
fi

PREPARE_ONLY=false
if [[ "$ACTION" == "--prepare-only" ]]; then
  PREPARE_ONLY=true
elif [[ "$ACTION" != "mpcc" ]]; then
  echo "usage: $0 [mpcc|--check-only|--prepare-only]" >&2
  exit 2
fi

GENERATED_DIR="${MPCC_GENERATED_DIR:-$HOME/.cache/f1tenth_residual_mpcc/acados_stable_v4_u_complex_std35_candidate}"
if [[ -z "${RESIDUAL_DYNAMICS_WS:-}" ]] \
   && [[ ! -f "$(dirname "$ROOT")/f1tenth_residual_ws/devel/setup.bash" ]]; then
  export RESIDUAL_DYNAMICS_WS="$ROOT"
fi
source "$ROOT/scripts/ros_env.sh"
# LocalizationStatus is generated by the localization workspace, which is not
# an underlay of the residual/controller workspaces on the car. Extend after
# ros_env.sh so the latter cannot reset the message's ROS/Python paths.
# Respect an explicit path. Otherwise support both the vehicle layout
# and this workstation's /home/tianbot/f1tenth/code layout.
LOCALIZATION_WS="${AUTO_RELAUNCH_LOCALIZATION_WS:-}"
if [[ -z "$LOCALIZATION_WS" ]]; then
  for candidate_path in \
    /home/tianbot/localization_main \
    "$(dirname "$ROOT")/localization_main" \
    /home/tianbot/f1tenth/code/localization_main; do
    if [[ -f "$candidate_path/devel/setup.bash" ]]; then
      LOCALIZATION_WS="$candidate_path"
      break
    fi
  done
fi
if [[ -z "$LOCALIZATION_WS" || ! -f "$LOCALIZATION_WS/devel/setup.bash" ]]; then
  echo "[FAIL] localization workspace setup is missing." >&2
  echo "       Set AUTO_RELAUNCH_LOCALIZATION_WS=/absolute/path/to/localization_main" >&2
  exit 1
fi
echo "[OK] localization workspace: $LOCALIZATION_WS"
MPCC_RESTORE_NOUNSET=false
case "$-" in
  *u*) MPCC_RESTORE_NOUNSET=true ;;
esac
set +u
source "$LOCALIZATION_WS/devel/setup.bash" --extend
if [[ "$MPCC_RESTORE_NOUNSET" == true ]]; then
  set -u
fi
unset MPCC_RESTORE_NOUNSET
export PYTHONPATH="$ROOT/src/f1tenth_dynamic_mpcc/python${PYTHONPATH:+:$PYTHONPATH}"
python3 -c 'from point_lio_sam_lighterbev.msg import LocalizationStatus' || {
  echo "[FAIL] point_lio_sam_lighterbev/LocalizationStatus is not importable" >&2
  exit 1
}
export MPCC_GENERATED_DIR="$GENERATED_DIR"
export MPCC_TRACK="$TRACK"
export MPCC_CONTROLLER_CONFIG="$CONTROLLER_CONFIG"
export MPCC_VEHICLE_CONFIG="$VEHICLE_CONFIG"
export MPCC_RESIDUAL_MODEL_PATH="$RESIDUAL"
export MPCC_RESIDUAL_FEATURE_SET="markov_v1"
export MPCC_COST_CONTOUR_OVERRIDE="45.0"
export MPCC_COST_HEADING_RACE_OVERRIDE="1.0"
export MPCC_COST_STEERING_COMMAND_RATE_OVERRIDE="0.60"
"$ROOT/scripts/ensure_acados_solvers.sh"

if [[ "$PREPARE_ONLY" == "true" ]]; then
  echo "[OK] U-complex candidate solvers are ready; hardware was not started"
  exit 0
fi

"$ROOT/scripts/check_mpcc_topics.sh"

RESIDUAL_MPCC_SPEED_CAP="${RESIDUAL_MPCC_SPEED_CAP:-5.0}"
if ! awk -v value="$RESIDUAL_MPCC_SPEED_CAP" \
  'BEGIN { exit !(value > 0.0 && value <= 5.0) }'; then
  echo "[FAIL] RESIDUAL_MPCC_SPEED_CAP must be in (0, 5.0]" >&2
  exit 2
fi

mkdir -p "$ROOT/log"
STAMP="$(date +%Y%m%d_%H%M%S)"
RECORD_PID=""
SHADOW_PID=""

cleanup_candidate() {
  if [[ -n "$RECORD_PID" ]] && kill -0 "$RECORD_PID" 2>/dev/null; then
    kill -INT "$RECORD_PID" 2>/dev/null || true
    wait "$RECORD_PID" 2>/dev/null || true
  fi
  if [[ -n "$SHADOW_PID" ]] && kill -0 "$SHADOW_PID" 2>/dev/null; then
    kill -TERM "$SHADOW_PID" 2>/dev/null || true
    wait "$SHADOW_PID" 2>/dev/null || true
  fi
}
trap cleanup_candidate EXIT
trap 'exit 130' INT TERM

if [[ "$MPCC_ENABLE_SHADOW" == "true" ]]; then
  "$AVOIDANCE" --foreground &
  SHADOW_PID=$!
  SHADOW_READY=false
  for _ in {1..300}; do
    if ! kill -0 "$SHADOW_PID" 2>/dev/null; then
      echo "[FAIL] perception/overtake shadow exited during startup" >&2
      exit 1
    fi
    NODES="$(rosnode list 2>/dev/null || true)"
    TOPICS_NOW="$(rostopic list 2>/dev/null || true)"
    if grep -qx '/opponent_perception' <<<"$NODES" \
       && grep -qx '/overtake_shadow' <<<"$NODES" \
       && grep -qx '/avoidance_state_visualizer' <<<"$NODES" \
       && grep -qx '/perception/targets_detailed' <<<"$TOPICS_NOW" \
       && grep -qx '/overtake/selected_path' <<<"$TOPICS_NOW" \
       && grep -qx '/overtake/diagnostics' <<<"$TOPICS_NOW" \
       && grep -qx '/avoidance/status' <<<"$TOPICS_NOW" \
       && grep -qx '/avoidance/local_plan_red' <<<"$TOPICS_NOW"; then
      SHADOW_READY=true
      break
    fi
    sleep 0.1
  done
  unset NODES TOPICS_NOW
  if [[ "$SHADOW_READY" != "true" ]]; then
    echo "[FAIL] perception/overtake shadow was not ready within 30 seconds" >&2
    exit 1
  fi
  echo "[SHADOW] enabled; command_authority=false"
else
  echo "[SHADOW] disabled"
fi

MPCC_RECORD_BAG="${MPCC_RECORD_BAG:-false}"
if [[ "$MPCC_RECORD_BAG" != "true" && "$MPCC_RECORD_BAG" != "false" ]]; then
  echo "[FAIL] MPCC_RECORD_BAG must be true or false" >&2
  exit 2
fi
export MPCC_RECORD_SHADOW_TOPICS="$MPCC_ENABLE_SHADOW"
if [[ "$MPCC_RECORD_BAG" == "true" ]]; then
  mkdir -p "$ROOT/bags"
  BAG_PATH="${MPCC_RECORD_BAG_PATH:-$ROOT/bags/stable_v4_u_complex_std35_candidate_${STAMP}.bag}"
  "$RECORDER" "$BAG_PATH" &
  RECORD_PID=$!
  echo "[RECORD] automatic-relaunch analysis bag -> $BAG_PATH"
else
  echo "[RECORD] disabled"
fi

echo "[U_COMPLEX] isolated candidate based on frozen Stable V4"
echo "[U_COMPLEX] final two U turns use low-curvature geometry and a continuous speed envelope"
echo "[BRAKE4_ASYM] normal publisher decel=4.0 m/s^2; fallback remains 4.0 m/s^2"
echo "[U_COMPLEX] raceline profile decel=3.2 m/s^2; publisher/fallback brake remains 4.0 m/s^2"
echo "[BRAKE4_ASYM] acceleration delay/tau=0.13/0.20 s; braking delay/tau=0.06/0.166 s"
echo "[AUTO_RELAUNCH] stableV3 residual + accepted 5/3 m/s raceline profile"
echo "[AUTO_RELAUNCH] operator workflow: hold E-stop -> carry/place -> release E-stop"
echo "[AUTO_RELAUNCH] carry: wheel<=0.10 + z/xy/yaw/tilt evidence; ground window=0.30 s"
echo "[AUTO_RELAUNCH] guarded release launch=2.0 m/s; checkpoint PP target=2.0 m/s; accel=2.4 m/s^2"
echo "[AUTO_RELAUNCH] global S + safe forward PP target; recovery angle<=60 deg"
echo "[AUTO_RELAUNCH] map-origin race grid: aligned launch=3.0 m/s; handoff=2.7 m/s"
echo "[AUTO_RELAUNCH] recovery PP: 2.0 m/s base, curvature/error adaptive >=1.2 m/s"
echo "[AUTO_RELAUNCH] PP->MPCC: adaptive speed + steering diff<=0.08 rad for 3 samples + 0.20 s blend"
echo "[U_COMPLEX] runtime cap=${RESIDUAL_MPCC_SPEED_CAP} m/s; fast zones=5.0, standard=3.5"
echo "[AUTO_RELAUNCH] hardware output=${AUTO_RELAUNCH_HARDWARE_COMMAND_TOPIC:-/tianracer/ackermann_cmd}"
echo "[AUTO_RELAUNCH] baseline auto-relaunch, original 5 m/s launcher and stableV3 remain unchanged"
echo "[WARNING] Hold the physical E-stop before launch. A valid ground placement arms the 2.0 m/s PP launch command."

LAUNCH_ARGS=(
  track:="$TRACK"
  controller_config:="$CONTROLLER_CONFIG"
  vehicle_config:="$VEHICLE_CONFIG"
  formulation:=mpcc
  allow_real_hardware:=true
  rviz:="${MPCC_REMOTE_RVIZ:-false}"
  runtime_speed_cap_mps:="$RESIDUAL_MPCC_SPEED_CAP"
  generated_dir:="$GENERATED_DIR"
  residual_model_path:="$RESIDUAL"
  residual_feature_set:=markov_v1
  hardware_command_topic:="${AUTO_RELAUNCH_HARDWARE_COMMAND_TOPIC:-/tianracer/ackermann_cmd}"
  telemetry_path:="$ROOT/log/hardware_stable_v4_u_complex_std35_candidate_${STAMP}.jsonl"
  lap_timer:="${AUTO_RELAUNCH_LAP_TIMER:-true}"
  lap_log_path:="$ROOT/log/laps_stable_v4_u_complex_std35_candidate_${STAMP}.csv"
)

if [[ -n "$RECORD_PID" || -n "$SHADOW_PID" ]]; then
  roslaunch f1tenth_dynamic_mpcc \
    hardware_mpcc_stable_v4_u_complex_std35_candidate.launch \
    "${LAUNCH_ARGS[@]}"
else
  exec roslaunch f1tenth_dynamic_mpcc \
    hardware_mpcc_stable_v4_u_complex_std35_candidate.launch \
    "${LAUNCH_ARGS[@]}"
fi
